/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuratorRouteImport } from './routes/curator'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HomeRouteImport } from './routes/home'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as CraftsIndexRouteImport } from './routes/crafts.index'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as CraftsCraftIdIndexRouteImport } from './routes/crafts.$craftId.index'
import { Route as CraftsCraftIdArRouteImport } from './routes/crafts.$craftId.ar'
import { Route as CraftsCraftIdLearnRouteImport } from './routes/crafts.$craftId.learn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratorRoute = CuratorRouteImport.update({
  id: '/curator',
  path: '/curator',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const CraftsIndexRoute = CraftsIndexRouteImport.update({
  id: '/crafts/',
  path: '/crafts/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const CraftsCraftIdIndexRoute = CraftsCraftIdIndexRouteImport.update({
  id: '/crafts/$craftId/',
  path: '/crafts/$craftId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsCraftIdArRoute = CraftsCraftIdArRouteImport.update({
  id: '/crafts/$craftId/ar',
  path: '/crafts/$craftId/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsCraftIdLearnRoute = CraftsCraftIdLearnRouteImport.update({
  id: '/crafts/$craftId/learn',
  path: '/crafts/$craftId/learn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/curator': typeof CuratorRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/mcp': typeof McpRoute
  '/progress': typeof ProgressRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/crafts/': typeof CraftsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/crafts/$craftId/ar': typeof CraftsCraftIdArRoute
  '/crafts/$craftId/learn': typeof CraftsCraftIdLearnRoute
  '/crafts/$craftId/': typeof CraftsCraftIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/curator': typeof CuratorRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/mcp': typeof McpRoute
  '/progress': typeof ProgressRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/crafts': typeof CraftsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/crafts/$craftId/ar': typeof CraftsCraftIdArRoute
  '/crafts/$craftId/learn': typeof CraftsCraftIdLearnRoute
  '/crafts/$craftId': typeof CraftsCraftIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/curator': typeof CuratorRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/mcp': typeof McpRoute
  '/progress': typeof ProgressRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/crafts/': typeof CraftsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/crafts/$craftId/ar': typeof CraftsCraftIdArRoute
  '/crafts/$craftId/learn': typeof CraftsCraftIdLearnRoute
  '/crafts/$craftId/': typeof CraftsCraftIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/curator'
    | '/help'
    | '/home'
    | '/mcp'
    | '/progress'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/crafts/'
    | '/.mcp/invoke-tool/$tool'
    | '/crafts/$craftId/ar'
    | '/crafts/$craftId/learn'
    | '/crafts/$craftId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/curator'
    | '/help'
    | '/home'
    | '/mcp'
    | '/progress'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/crafts'
    | '/.mcp/invoke-tool/$tool'
    | '/crafts/$craftId/ar'
    | '/crafts/$craftId/learn'
    | '/crafts/$craftId'
  id:
    | '__root__'
    | '/'
    | '/curator'
    | '/help'
    | '/home'
    | '/mcp'
    | '/progress'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/crafts/'
    | '/.mcp/invoke-tool/$tool'
    | '/crafts/$craftId/ar'
    | '/crafts/$craftId/learn'
    | '/crafts/$craftId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuratorRoute: typeof CuratorRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  McpRoute: typeof McpRoute
  ProgressRoute: typeof ProgressRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CraftsIndexRoute: typeof CraftsIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  CraftsCraftIdArRoute: typeof CraftsCraftIdArRoute
  CraftsCraftIdLearnRoute: typeof CraftsCraftIdLearnRoute
  CraftsCraftIdIndexRoute: typeof CraftsCraftIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curator': {
      id: '/curator'
      path: '/curator'
      fullPath: '/curator'
      preLoaderRoute: typeof CuratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafts/': {
      id: '/crafts/'
      path: '/crafts'
      fullPath: '/crafts/'
      preLoaderRoute: typeof CraftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafts/$craftId/': {
      id: '/crafts/$craftId/'
      path: '/crafts/$craftId'
      fullPath: '/crafts/$craftId/'
      preLoaderRoute: typeof CraftsCraftIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafts/$craftId/ar': {
      id: '/crafts/$craftId/ar'
      path: '/crafts/$craftId/ar'
      fullPath: '/crafts/$craftId/ar'
      preLoaderRoute: typeof CraftsCraftIdArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafts/$craftId/learn': {
      id: '/crafts/$craftId/learn'
      path: '/crafts/$craftId/learn'
      fullPath: '/crafts/$craftId/learn'
      preLoaderRoute: typeof CraftsCraftIdLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuratorRoute: CuratorRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  McpRoute: McpRoute,
  ProgressRoute: ProgressRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CraftsIndexRoute: CraftsIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  CraftsCraftIdArRoute: CraftsCraftIdArRoute,
  CraftsCraftIdLearnRoute: CraftsCraftIdLearnRoute,
  CraftsCraftIdIndexRoute: CraftsCraftIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
